### ISSUE TITLE
issue with usher --version 

### ISSUE THREAD

**Issue by kapsakcj** [yatisht/usher#100]
Installed `usher` via (bio)conda, version 3.2.0-0, but `usher --version` does not appropriately output the version

Here's what I'm seeing:
```
$ conda list | grep usher
usher                     0.3.2                h7b4d82f_0    bioconda

$ usher --version
UShER (v..)
```

**Comment by kapsakcj** [comment]
I appreciate the effort here, Yatish. Here's what I'm seeing now. The numbers do show up now, but, they are for the previous patch version.

```
$ conda install -c bioconda usher==0.3.4-0

<all output redacted>

$ conda list | grep usher
usher                     0.3.4                h7b4d82f_0    bioconda

$ usher --version
UShER (v0.3.3)
```

**Comment by yatisht** [comment]
Hi Curtis,

Firstly, thanks a lot for pointing out this issue. I was trying to come up with a solution with which I don't have to update the version at more than one place, but none of them worked. So I have reverted to a manual version tagging and updating for now, and created a new release v0.3.5. This update should be available on conda by tomorrow, and hopefully the version numbers would appear correctly with usher henceforth. 

Best,
Yatish

**Comment by kapsakcj** [comment]
great, thank you!

Versioning is often a pain, so thank you for enduring through it!

**Comment by yatisht** [comment]
Yes, I wish it was a bit simpler with something like GitHub Actions. And no worries, it would hopefully be OK from now on. Thanks.

**Comment by yatisht** [comment]
Hi Curtis,

I think this issue is fixed now, even on bioconda. I'll close it for now, but please feel free to reopen it if you still face issues. Thanks once again for bringing this to our attention.

-Yatish
