### ISSUE TITLE
matOptimize tutorial/test crashes with a segmentation fault

### ISSUE THREAD

**Issue by moskalenko** [yatisht/usher#122]
Hi,

On a 64-bit linux system (RHEL7) the 

wget http://hgdownload.soe.ucsc.edu/goldenPath/wuhCor1/UShER_SARS-CoV-2/2021/05/25/public-2021-05-25.all.masked.pb.gz
matOptimize -i public-2021-05-25.all.masked.pb.gz -o optimized-public-2021-05-25.all.masked.pb.gz -T 32 -r 4

part of the post-installation test for usher segfaults:

`
$ wget http://hgdownload.soe.ucsc.edu/goldenPath/wuhCor1/UShER_SARS-CoV-2/2021/05/25/public-2021-05-25.all.masked.pb.gz
--2021-08-06 09:57:41--  http://hgdownload.soe.ucsc.edu/goldenPath/wuhCor1/UShER_SARS-CoV-2/2021/05/25/public-2021-05-25.all.masked.pb.gz
Resolving hgdownload.soe.ucsc.edu (hgdownload.soe.ucsc.edu)... 128.114.119.163
Connecting to hgdownload.soe.ucsc.edu (hgdownload.soe.ucsc.edu)|128.114.119.163|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 13692694 (13M) [application/x-gzip]
Saving to: ‘public-2021-05-25.all.masked.pb.gz’

100%[=====================================================================================================================>] 13,692,694  16.2MB/s   in 0.8s

2021-08-06 09:57:42 (16.2 MB/s) - ‘public-2021-05-25.all.masked.pb.gz’ saved [13692694/13692694]

$ matOptimize -i public-2021-05-25.all.masked.pb.gz -o optimized-public-2021-05-25.all.masked.pb.gz -T 8 -r 4
Summary:
Load both starting tree and sample variant from public-2021-05-25.all.masked.pb.gz last modified: Wed May 26 06:28:51 2021
Will output final protobuf to optimized-public-2021-05-25.all.masked.pb.gz .
Will output intermediate protobuf to optimized-public-2021-05-25.all.masked.pb.gzintermediateBYVo6M.pb.
Will consider SPR moves within a radius of 4.
Will stop search and apply all moves found when 1000 moves are found
Will save intermediate result every 10 minutes
Run kill -s SIGUSR2 29376 to apply all the move found immediately, then output and exit.
Using 8 threads.
Will only consider nodes carrying mutations that occured more than twice anywhere in the tree.
Start loading protobuf
WARNING: This pb does not include any metadata. Filling in default values
WARNING: Tree found empty!
Finished loading protobuf, start reassigning states
Segmentation fault
`

**Comment by russcd** [comment]
I believe this issue is with matOptimize reading a gzipped pb. On my machine (Ubuntu 20.04) this solved the problem. Can you try gunzipping the pb first?

We will look into why this is not working and update the code soon. Leaving this open until that gets resolved.

**Comment by moskalenko** [comment]
Confirmed. Gunzipping the protobuf file prevents the segfault.

**Comment by yatisht** [comment]
Great, sorry about that – I'll make the correction on the wiki. `matOptimize` currently does not gzipped files. @yceh we should add the support.
