### ISSUE TITLE
output the details of profitable SPR moves

### ISSUE THREAD

**Issue by roblanf** [yatisht/usher#132]
This is (obviously) a wish-list enhancement. Also obviously, *none* of this is important. It's bottom-of-the-pile stuff.

In terms of tuning parameters for continuous updating, it would be useful to know the details of all detected profitable SPR moves, as well as whether they were applied. 

One option would be to output a summary of the  _applied_ move sizes at the end of each iteration to stdout, something like:

```
234 profitable moves applied, 
move sizes: min: 1, mean: 1.4, median 1, max: 1452
move parsimony improvement: min: 1, mean: 5, median: 3, max: 32
sequences affected per move: min: 1, mean: 4, median: 3, max: 25898
```

and then optionally output a csv with more details, e.g.

* iteration
* move size (i.e. distance between affected branches)
* move parsimony improvement
* number of sequences moved
* move applied (TRUE/FALSE)

**Comment by yatisht** [comment]
Thanks for the suggestion. I agree that this would be very useful to output. @yceh I assume this is not too difficult to add as an optional output?

**Comment by yatisht** [comment]
Closing this issue, since it's been resolved in the PR mentioned above. Thanks.
