### ISSUE TITLE
feature request: don't place high parsimony samples

### ISSUE THREAD

**Issue by roblanf** [yatisht/usher#145]
Currently there's an option to not place uncertain samples:

```
  -e [ --max-uncertainty-per-sample ] arg (=1000000)
                                        Maximum number of equally parsimonious 
                                        placements allowed per sample beyond 
                                        which the sample is ignored

```

My request (as always, I know everyone is busy, I am probably the only person who wants this option, and I am very happy to be completely ignored) is for something that won't place really rubbish samples that are obviously garbage:

```
  -E [ --max-parsimony-per-sample ] arg (=1000000)
                                        Maximum parsimony score of most parsimonious 
                                        placement allowed per sample beyond 
                                        which the sample is ignored

```

This would allow one to try and place many samples, but to ignore samples that were missed in prior filtering steps but that parsimony shows are obviously no good. E.g. those on terminal branches >100, which I sometimes see and then have to prune out later.

**Comment by russcd** [comment]
@AngieHinrichs could we add this filter to the public tree workflow?

**Comment by AngieHinrichs** [comment]
Sure.  Currently I'm filtering post-placement with `matUtils extract --max-parsimony 20 --max-branch-length 30`.   So just to confirm, I'll be adding `--max-parsimony-per-sample 20` to usher, and then just `matUtils extract --max-branch-length 30`.

**Comment by russcd** [comment]
This option is available in the latest commits. Thanks @yatisht !
