### ISSUE TITLE
Taxodium export: inconsistency with original behaviour w.r.t. residue colouring

### ISSUE THREAD

**Issue by theosanderson** [yatisht/usher#149]
Hey folks,

Continue to be incredibly excited by what @amkram has put together. 

I noticed a small difference between how I do things and what UShER does, which is worth flagging just so you know about it. It's not a bug, because Taxodium's behaviour isn't documented, and in some ways it's actually quite cool.

Taxodium includes a feature to colour by the amino acid residue at a position. To achieve this, we basically trace back each node through the tree to figure out what residue it should be at a particular node.

For [UShER trees](https://taxodium.org/?search=%5B%7B%22id%22%3A0.123%2C%22category%22%3A%22genbanks%22%2C%22value%22%3A%22MZ639045.1%22%2C%22enabled%22%3Atrue%2C%22aa_final%22%3A%22any%22%2C%22min_tips%22%3A1%2C%22aa_gene%22%3A%22S%22%2C%22search_for_ids%22%3A%22MZ639045.1%22%7D%5D&colourBy=%7B%22variable%22%3A%22aa%22%2C%22gene%22%3A%22S%22%2C%22colourLines%22%3Afalse%2C%22residue%22%3A%22484%22%7D&protoUrl=https%3A%2F%2Fhgwdev.gi.ucsc.edu%2F~angie%2FUShER_SARS-CoV-2%2F2021%2F08%2F18%2Fpublic-2021-08-18.all.masked.taxodium.pb.gz) once traced back to the reference sequence there are no more mutations, and so the color becomes gray. Whereas [in my implementation](https://taxodium.org/?protoUrl=%2Fnodelist.pb&search=%5B%7B%22id%22%3A0.123%2C%22category%22%3A%22lineage%22%2C%22value%22%3A%22%22%2C%22enabled%22%3Atrue%2C%22aa_final%22%3A%22any%22%2C%22min_tips%22%3A1%2C%22aa_gene%22%3A%22S%22%2C%22search_for_ids%22%3A%22%22%7D%5D&colourBy=%7B%22variable%22%3A%22aa%22%2C%22gene%22%3A%22S%22%2C%22colourLines%22%3Afalse%2C%22residue%22%3A%22484%22%7D) the reference sequence is shown.

The reason for this difference is that my code implements a [hacky fix](https://github.com/theosanderson/taxodium/blob/c5368d5bd401b109450decdb02d830b6ce76c08f/data_processing/usher_processing.py#L159) of creating a "mutation" for every wild-type codon to its reference sequence, and applying this mutation to the root node, which isn't implemented in UShER.

So the options would be:

- keep current behaviour (good for making unmutated versions disappear)
- change UShER code to implement the hacky fix
- think of another approach and implement it in Taxodium (possibly with some changes needed to UShER too).

Really just flagging in case you weren't aware and to explain the background. Let me know if you'd prefer option 3 and we can talk about what that might look like.

**Comment by russcd** [comment]
I had not noticed this! 

I think we should modify this behavior. @amkram can you do that?

**Comment by amkram** [comment]
Thanks @theosanderson for pointing this out! It does make sense to keep the coloring consistent per amino acid, so I can definitely add that fix.

**Comment by theosanderson** [comment]
:)

FYI the genome source seems to have ORF1a and ORF1ab leading to some duplication
![image](https://user-images.githubusercontent.com/19732295/132418119-33ef61b2-1fa8-403b-a0d4-7404586d3b53.png)

**Comment by amkram** [comment]
Hey @theosanderson ,

This fix is now implemented along with generic metadata (#157).

As for the Orf1a/Orf1ab duplications, I believe the Taxodium pb releases at the [dev site](https://hgwdev.gi.ucsc.edu/~angie/UShER_SARS-CoV-2/) are currently being built with this [gtf file](https://hgdownload.soe.ucsc.edu/goldenPath/wuhCor1/bigZips/genes/) which has both Orf1a and the longer Orf1ab (which includes 1a). It seems that there is some variance with start/end positions when splitting Orf1ab into Orf1a and Orf1b depending on where you look. If you could pass along the file/coordinates you are using, I can get it into the right format and hopefully @AngieHinrichs can plug it into to the build process?

**Comment by theosanderson** [comment]
I'm using https://github.com/theosanderson/taxodium/blob/master/data_processing/cov2_genome.py but not saying that's particularly special, I just think the current behaviour on the dev site is maybe unexpected. But like, it's not a big deal at all, just something I happened to spot :)

**Comment by theosanderson** [comment]
And awesome stuff re generic metadata!! I'm afraid these won't be surfaced immediately, but hopefully very soon!
