### ISSUE TITLE
Taxodium export: change to format of metadata for countries/lineages

### ISSUE THREAD

**Issue by theosanderson** [yatisht/usher#154]
I've changed how metadata works for Taxodium. This will help with a bunch of things we're mutually interested in but ultimately needs a change to the export function. Sorry for the fact that nothing was fully finalised at the time when @amkram  implemented the logic.

Basically rather than countries and lineages being specially coded I want to roll them into a generic metadata object that can contain any item where there is one for each node.

The change is https://github.com/theosanderson/taxodium/commit/9ef607a41bbf6991f07c6ded44863be3cc992e39

I renamed the proto to https://github.com/theosanderson/taxodium/blob/master/public/taxodium.proto and made the changes

Possibly the easiest thing is to look at the diff to `usher_processing.py`

This unlocks the ability to add other metadata items in a hopefully relatively self-explanatory way.

But the client side for the novel items is not implemented atm.

The change is currently implemented in a backwards-compatible way, but I might break that in the future.

**Comment by amkram** [comment]
This will be super helpful, thanks! I'll get that added to the export function soon.

**Comment by theosanderson** [comment]
Amazing! These won't be immediately surfaced, but working on that!
