### ISSUE TITLE
UShER requires genotype in VCF

### ISSUE THREAD

**Issue by pvanheus** [yatisht/usher#164]
UShER insists that a VCF file has a GenoType column (the code is [here](https://github.com/yatisht/usher/blob/master/src/usher.cpp#L217)) even though GenoType is optional in the VCF [specification](https://samtools.github.io/hts-specs/VCFv4.2.pdf).

**Comment by AngieHinrichs** [comment]
The sample name is taken from the corresponding column in the header's #CHROM line.  Any suggestion for what to use as the sample name if there are no sample genotype columns?

Also, what if there are multiple alternate alleles?  If usher is assuming there is only one sample that always has the alternate allele for every mutation in the VCF file, then it would have to make an arbitrary choice like always taking the first ALT if there are more than one.  A reasonable behavior could be defined, but I don't think it would make sense for UShER to support the entire VCF spec (breakends anyone?). #93

**Comment by AngieHinrichs** [comment]
Oh... thanks for providing the examples.  So usher does not complain when there are no actual sample genotype columns, but still a GT column.  But it probably does not produce useful results in that case either since there are no samples to place?  Let me try it here...

**Comment by AngieHinrichs** [comment]
In the meantime, in case it helps, here is a quick sed command that tacks on a sample genotype column with an arbitrary name and the first alternate allele for every mutation (in the `#CHROM` line, it also tacks on GT which was missing):
```
sed -re '/^#CHROM/ s/$/\tGT\tTheOneSample/;
         /^[^#]/ s/$/\t1/' ERR5931005_with_GT.vcf > ERR5931005_with_GT_and_one_sample.vcf.txt
```
usher does produce a placement for TheOneSample in that VCF.
