### ISSUE TITLE
Taxodium export segfaults with empty gisaid_accession column

### ISSUE THREAD

**Issue by theosanderson** [yatisht/usher#168]
Hi,

I tried a Taxodium export using a `metadata.tsv` with a `gisaid_accession` column present but with values of empty strings throughout. This gave a segfault. Switching to "none" seemed to fix this. Not a big deal of course! The better fix is for me to update Taxodium not to need this column. But raising for info.

Thanks

T

**Comment by yatisht** [comment]
@amkram

**Comment by amkram** [comment]
Thanks for pointing this out, I'll look into it. I think we should keep this open to ensure we handle empty data properly.

**Comment by theosanderson** [comment]
Hey @amkram ,

I'm really really sorry if I've sent you on a wild goose chase. I really felt I'd narrowed this down, or I wouldn't have posted it, but I may well have been wrong.

I'm gonna close this until I have a chance to chase this again because I've long since overwritten those original files. If I don't reopen it, then sorry for wasting your time.

Thanks again for looking!
