### ISSUE TITLE
Metadata: duplicated lines in metadata.tsv

### ISSUE THREAD

**Issue by theosanderson** [yatisht/usher#173]
Hey @AngieHinrichs, fyi there are about 15k strains that appear twice in https://hgwdev.gi.ucsc.edu/~angie/UShER_SARS-CoV-2/public-latest.metadata.tsv.gz and look to have the same data in each case. Not a big deal at all, but can cause confusion when one goes joining if one isn't aware. No pressure from me to fix. Thanks as ever.

**Comment by theosanderson** [comment]
On reflection this isn't really the right repo for this - apologies - I will stick to other venues in future :)

**Comment by AngieHinrichs** [comment]
Oh, that is sloppy.  I will clean it up.

Yeah, it's certainly not the fault of any code in this repo.  :)  The scripts that update the UCSC tree & metadata are technically on github (https://github.com/ucscGenomeBrowser/kent/tree/master/src/hg/utils/otto/sarscov2phylo) but that github repo is just a mirror.  We (UCSC Genome Browser team) use internal systems for development and tracking.  

Feel free to email me with any questions/bug reports about the download files.  Or if you prefer a public forum so I can be held accountable :) the Genome Browser preferred method is email to our public archived user support list, genome@soe.ucsc.edu.
