### ISSUE TITLE
Query about summarising mutation information with matUtils

### ISSUE THREAD

**Issue by charlesfoster** [yatisht/usher#193]
Hi,
Just wondering, what's the best way to use `matUtils` to correctly determine the number of leaves in the global tree that have a certain mutation? 

My first attempt was as follows:

```
matUtils summary -i public-latest.all.masked.pb.gz -m all_mutations.tsv
```
Reported occurrence for my mutation of interest:
ID | occurrence
-- | --
G29179T | **616**

I also tried: 

```
matUtils extract -i public-latest.all.masked.pb.gz -m G29179T -o mutation_tree.pb.gz
```

The above command extracts a subtree of **8814** samples. If I open the subtree in auspice.us and then filter by my mutation of interest, it shows "8804 of 8814 samples".

Which approach is the correct way to find the statistic of "X leaves/tips in the tree possess the Y mutation"?

As an aside, while trying to manually check the 8814 samples for the mutation of interest by creating a multifasta file, I attempted to follow the `vcfindex` and `vcf2fasta` steps from here: https://usher-wiki.readthedocs.io/en/latest/matUtils.html. Commands:

```
matUtils extract -i public-latest.all.masked.pb.gz -m G29179T -v G29179T_samples.vcf
vcfindex G29179T_samples.vcf
vcf2fasta -f $REF G29179T_samples.vcf 
```

Error:
```
could not open England/BRIS-1219B2/2020|FR996369.1|2020-03-15_NC_045512v2:0.fa for writing, exiting
```

It appears that the slashes in GISAID virus names prevents the commands from working. The command was attempting to write a file called `2020|FR996369.1|2020-03-15_NC_045512v2:0.fa` in a directory called `England/BRIS-1219B2/`, which obviously didn't exist. Might be worth noting these issues in the wiki...

Thanks,
Charles

**Comment by jmcbroome** [comment]
Hi Charles- For your first question, your second attempt is very close and should be the current best approach. Your true answer appears to be 8804. The fact that this includes a few additional samples does reveal that we have a flaw in our mutation selection routine, however, which I am currently investigating.

In regards to your first attempt with summary, I'm taking note that a count of leaves would be an additional appropriate output for that method, and may implement that in our next release. Ideally this would be the correct approach.

For the last point, I'm not overly familiar with vcfindex and vcf2fasta (perhaps my collaborators can shed some light on this), but can note that you can get simple counts of samples with mutations via command line tools e.g.

```
grep "G29179T" mutation_tree.vcf | cut -f9- | grep -o "1"  | wc -l
```

Which, on today's tree, yields the magic number of 8804.

Thank you for highlighting this issue and hope this helps- 

Jakob M

**Comment by charlesfoster** [comment]
That's fantastic, thanks for the explanation and the update. Just for clarity, is the occurrence count of 616 in the first method intended to note the number of nodes in the protobuf tree annotated with the G29179T mutation (rather than the number of leaves)?

**Comment by jmcbroome** [comment]
That's correct, yes.

**Comment by yatisht** [comment]
Closing this issue since I assume this is resolved. Thanks!
