### ISSUE TITLE
Update Nextstrain clades to include 21K (Omicron)

### ISSUE THREAD

**Issue by corneliusroemer** [yatisht/usher#199]
I'm not sure whether this will happen automatically or not, but so far, you're not calling Omicron as Nextstrain clade 21K but 20B instead.

![image](https://user-images.githubusercontent.com/25161793/143681609-41a21e18-a8f6-4f99-ab8b-07d308958c0d.png)

**Comment by AngieHinrichs** [comment]
Not automatic, thanks for the reminder!  On our test server, the GISAID+public tree is updated; public-only tree should be updated within a couple hours.  Tomorrow both should be updated on our main site.

**Comment by yatisht** [comment]
I think this is resolved now. Thanks for raising this, @corneliusroemer!
