### ISSUE TITLE
Problem with UShER web server - unbalanced parenthesis warning/error

### ISSUE THREAD

**Issue by flashton2003** [yatisht/usher#205]
Hello,

Apologies if this is the wrong place to report problems with the [UShER web server](https://hgwdev.gi.ucsc.edu/cgi-bin/hgPhyloPlace), but there didn't seem to be an UShER specific place to raise issues on the UCSC genome browser site.

When I upload my genomes to UShER I get the following error, and no results.

`unbalanced parenthesis at (;_if_the_virus_has_strain_name_enter_it_at_/strain_and_make_/isolate_empty.|LC666806.1|2021-04-02:0,Hu/Kng/207720|LC666807.1|2021-04-02:1):1,(((IMS-10261-CVDP-D85D6BB9-D578-44F3-B640-150641B424F6|OU098092.1|2021-03-08:0,IMS-10261-CVDP-5ACA4BF7-A5E9-4C01-A0AB-91404433B122|OU122709.1|2021-03-28):1,IMS-10267-CVDP-A362F978-145B-400E-B48F-1216B2E84F5E|OU107956.1|2021-03-11:0):1,((node_46887_condensed_3_leaves:0):1,IMS-10116-CVDP-456A4B5B-C926-4F52-8B5D-DBFB086DD023|OU164696.1|2021-05-07,node_41476_condensed_2_leaves:0):3,(node_41477_condensed_4_leaves:0):2,(node_41478_condensed_6_leaves:0):1,IMS-10267-CVDP-D25EFC84-820C-41E8-838C-CDDA4CB37EED|OU122344.1|2021-03-25,IMS-10087-CVDP-8323A8FD-36B7-4E4D-A9E3-B19DE887AD77|OU094423.1|2021-03-03,IMS-10267-CVDP-82C8EF94-EC52-4D86-9D9B-A55B4636E943|OU130087.1|2021-04-03,node_36514_condensed_4_leaves:0):0,USA/CA-CDC-FG-010306/2021|OL321200.1|2021-03-18,England/CAMC-13D2B88/2021|OU066501.1|2021-03-10,node[...]`

None of my sample names have parentheses in, so it might be something in one of the samples in the database? It happens with both the GISAID and NCBI trees.

Thanks,

Phil Ashton

p.s. I'm happy to share the input file by email if that helps.

**Comment by flashton2003** [comment]
Oh, and I just checked and the error is happening with the example dataset given on the UShER website so probably not an issue with my file.

**Comment by TheWileyB** [comment]
I'm experiencing the same issue. Similar or identical error messages are generated from the main website and both European and Asian mirrors, as well as ShUShER. I've submitted single fasta and vcf, multifasta, the default example file, and the complete reference fasta (NC_045512.2). Still no luck

**Comment by AngieHinrichs** [comment]
Ugh, sorry about that and thanks for reporting it.  At first glance it looks like a very odd sequence name was imported from GenBank and added to the tree, then causing parsing problems for usher when reading the tree back in.  I will fix this ASAP.

**Comment by AngieHinrichs** [comment]
Things one doesn't expect to find as isolate name... https://www.ncbi.nlm.nih.gov/nuccore/LC666806

**Comment by AngieHinrichs** [comment]
This is fixed on the test server to which you linked above, and should be fixed in an hour on our [main site](https://genome.ucsc.edu/cgi-bin/hgPhyloPlace).  Fortunately it is only the web interface's parsing that was thrown off my the extraneous ';' character (which is supposed to signal end-of-tree in a Newick format file), not usher/matUtils parsing.  

When there is a problem with the web interface or especially in the Genome Browser view that the results link to, genome@soe.ucsc.edu is a good place to report errors, but this works too.

**Comment by flashton2003** [comment]
Haha wow. The edge cases you come across when you're dealing with millions of genomes!

Thanks for the quick fix Angie, I really appreciate it as I'm presenting an UShER analysis this morning.

**Comment by TheWileyB** [comment]
Wow, great find @AngieHinrichs. The last thing I was expecting with this situation was to have a laugh. Thanks very much for the rapid response, fix, and explanation.

**Comment by yatisht** [comment]
Funny (and must also be frustrating for @AngieHinrichs). Thanks all. I am closing this issue now.
