### ISSUE TITLE
Not all nodes are shown in the tsv file generated by the function --translate 

### ISSUE THREAD

**Issue by akograf** [yatisht/usher#206]
Hello, 
Congratulations for this wonderful tool!
I'm using matUtils (summary --translate) to generate a mutation table and I though that all nodes would be included, however some are not. Is it an expected behavior?

Thanks, 
Tiago

**Comment by yatisht** [comment]
Adding @amkram who has developed matUtils summary --translate.

**Comment by amkram** [comment]
Hi @akograf ,

The current intended behavior of `summary --translate`  is to output mutations within coding regions (including synonymous mutations). So nodes that have either zero nucleotide mutations or mutations outside CDS would not be in the resulting TSV. Please let me know if this doesn't match the behavior you are observing.

**Comment by akograf** [comment]
Thanks @amkram. 
For what I could understand of Usher method, all nodes in a MAT has an assigned mutation. Or is it not always the case?
Thus, the nodes I cannot see in the mutations TSV might be mutations outside CDS. Indeed, there are very few nodes that are not in the mutations TSV.

Thanks, again

**Comment by amkram** [comment]
It is possible for a node to have no mutations annotated in the MAT object -- consider the first figure [here](https://usher-wiki.readthedocs.io/en/latest/UShER.html#methodology). In that case, samples S2, S3, and S4 are identical to their parent internal node (2), and thus no mutation would be stored in the MAT for those nodes. Hope that helps.
