### ISSUE TITLE
Recommended way to visualize a huge mutation-annotated tree?

### ISSUE THREAD

**Issue by fritzo** [yatisht/usher#207]
I love that UShER allows me to work with enormous phylogenetic trees with e.g. 4million nodes. Can anyone recommend a method to visualize these enormous trees?

**Comment by russcd** [comment]
Hi @fritzo, have you had a look at taxonium (cov2tree.org)? You can create the input file from your UShER MAT using matUtils. Check out https://github.com/yatisht/usher/tree/master/workflows for a simple workflow that will do this.

**Comment by fritzo** [comment]
Thanks @russcd, I'll check out those tools!
