### ISSUE TITLE
usher: undefined symbol: _ZN5boost9iostreams4zlib8deflatedE

### ISSUE THREAD

**Issue by jwni2018** [yatisht/usher#209]
Has anyone seen this error? Tried installation with miniconda3 under Ubuntu 14.04 and 18.04, same error message.

**Comment by jwni2018** [comment]
The missing symbol was in boost-cpp-1.74.0-h359cf19_5/lib/libboost_iostreams.so.1.74.0 last month, but lost it from boost-cpp-1.74.0-h359cf19_6/lib/libboost_iostreams.so.1.74.0 now.

**Comment by yatisht** [comment]
Thank you for looking into it. So is this resolved for you now?

**Comment by jwni2018** [comment]
The updated libboost_iostreams.so.1.74.0 file is automatically pulled by miniconda3 install process, you will always run into this problem if you install from a fresh copy of miniconda3 base package. Can we have a new new usher built from the updated libboost_iostreams.so.1.74.0 for conda install?

**Comment by jwni2018** [comment]
conda-forge had a new built for boost-cpp=1.74.0 which resolved the issue, as mentioned in https://github.com/conda-forge/rdkit-feedstock/issues/93.
So the current issue can be closed.

**Comment by yatisht** [comment]
Thanks.
