### ISSUE TITLE
Seg-faults with some absolute paths to matUtils extract

### ISSUE THREAD

**Issue by theosanderson** [yatisht/usher#211]
If I use absolute paths with `matUtils extract -t` to get a Newick file I get a seg-fault. It took me a little while to understand that this was the cause rather than some other issue with my config, so could be a useful fix
```
matUtils extract -i public-latest.all.masked.pb -t /home/theo/tree.nwk
Loading input MAT file public-latest.all.masked.pb.
Completed in 12594 msec

Checking for and applying sample selection arguments
Completed in 0 msec

No sample selection arguments passed; using full input tree for further output.
Completed in 742 msec

Generating Newick file of final tree
Segmentation fault
```

I also tried the clades function randomly and got similarish results - no segfault but I was not able to find the file in either location:

```
matUtils extract -i public-latest.all.masked.pb -C /tmp/bla.clades
Loading input MAT file public-latest.all.masked.pb.
Completed in 10541 msec

Checking for and applying sample selection arguments
Completed in 0 msec

No sample selection arguments passed; using full input tree for further output.
Completed in 668 msec

Writing clade paths to /home/theo/treeShears//tmp/bla.clades
Completed in 746 msec
```

**Comment by russcd** [comment]
Thanks, Theo. @jmcbroome can you take a look at this?

**Comment by jmcbroome** [comment]
Hi Theo- matUtils extract uses an output directory option (-d) that defaults to the current directory. When creating paths for output files, it prepends this value (e.g. calling matUtils extract -i something.pb -t something.nwk creates a newick file at path/to/current/directory/something.nwk). You can see this happening in the output of your second command. To use absolute paths, you can set -d to "/" and writing paths accordingly (e.g. matUtils extract -i public-latest.all.masked.pb -d / -t home/theo/tree.nwk). Let me know if this will work for you or if you encounter further issues!

**Comment by theosanderson** [comment]
Ah thanks! That makes total sense. I guess one could put out an error message for paths starting with `/`, but life is probably too short. Thanks again!

**Comment by theosanderson** [comment]
Kind of related to this (and just flagging for info), it seems like I have to specify the fasta file (`-f`) and the GTF file (`-g`) relative to this specified output directory, which I guess I wouldn't have expected as they seem more input. Now that I understand it's not a prob!

**Comment by aofarrel** [comment]
Possible regression in v0.6.6: `-d` doesn't seem to work properly in conjunction with `-o` and `-j` (#437)
