### ISSUE TITLE
ENH: allow placement of sequence fragments shorter than 10k bp

### ISSUE THREAD

**Issue by corneliusroemer** [yatisht/usher#221]
I wanted to place a potential recombinant fragment that's 9k bp long.

Unfortunately, Usher doesn't seem to support this at the moment.

Shouldn't Usher still be able to place that fragment? Sure, it's less exact, but maybe together with a warning this could be enabled? Or a tickbox to enable?

Don't you do this sort of short fragment placement anyways with your recombinant detection algorithm?

This is the message I get: 
<img width="816" alt="image" src="https://user-images.githubusercontent.com/25161793/158079479-8d9415df-cd99-4859-b2cc-817abe2e1fa0.png">

**Comment by russcd** [comment]
I suggest trying RIPPLES if you think a sample might be recombinant. Given the age of the issue, it looks close-able.
