### ISSUE TITLE
BUG: Multiple mutations in one codon cause can cause false amino acid mutation

### ISSUE THREAD

**Issue by corneliusroemer** [yatisht/usher#222]
When looking at sequence `Iran/AN127/2022|EPI_ISL_10195257`, I noticed that it was falsely annotated with `Q498*`.

Nextclade annotates it with `Q498Q`:
![image](https://user-images.githubusercontent.com/25161793/158714143-43b55c21-9c05-4416-85f2-be38bb87eb5b.png)

The reason for Usher's false annotation seems to be the presence of two mutations in one codon. 

On an internal branch, I could even see two mutations listed side by side `Q498H, Q498*` which is clearly not possible.

How do you deal with multiple mutations in one codon? Is this a known limitation by design?

![image](https://user-images.githubusercontent.com/25161793/158714299-346759f5-2b1f-4927-ad4f-950146ca07a9.png)

![image](https://user-images.githubusercontent.com/25161793/158714304-188529a7-3aa8-42cc-8c03-4bcf13cbf00f.png)

**Comment by AngieHinrichs** [comment]
Sorry, the web interface uses simple code that translates each nucleotide substitution into its corresponding amino acid substitution independently.  I'll add it to the list of badly needed improvements but am not sure when I'll have time to work on it.

**Comment by AngieHinrichs** [comment]
I believe this is fixed on dev.usher.bio now - CV.2 and XBB.1.5 are good for testing this.  Also a cluster in XBC.2 that has a (probably false) reversion on 23019 that causes S:P486L (e.g. Brunei/7722014505/2022|EPI_ISL_15696712|2022-10-10), with one member of that cluster regaining T23019C restoring 486P (Brunei/7722017695/2022|EPI_ISL_16231620|2022-11-28).

**Comment by corneliusroemer** [comment]
Exciting news, thanks so much @AngieHinrichs! I'll watch out for possible regressions.

**Comment by russcd** [comment]
Looks to be working to me. Closing for now.
