### ISSUE TITLE
Firefox Browser: Unsecure site

### ISSUE THREAD

**Issue by FedeGueli** [yatisht/usher#261]
Hi since yesterday i have issues in getting back results from my queries on Usher both from CovSpectrum nd to less extent from Fast uploading, i ve tried with Mozzilla Firefox and it gave me back a message unsure site contact the site admin.
So i am doing that. Maybe it is just my PC. but i thought it was right  to inform  you.
Thx for your work
![Schermata 2022-08-10 alle 09 02 25](https://user-images.githubusercontent.com/87669813/183836365-7c56e413-30e8-49a8-a868-c84759cf18f9.png)
.

**Comment by AngieHinrichs** [comment]
Hi @FedeGueli, sorry it's not working for you.  Can I ask, how many sequences are you uploading at one time?  Or could you share a CoVSpectrum query that is failing?

**Comment by FedeGueli** [comment]
Hi @AngieHinrichs also one both uploading fasta or with epi_isls.

**Comment by FedeGueli** [comment]
https://cov-spectrum.org/explore/World/AllSamples/Past2W/variants?variantQuery=NextCladePangoLineage%3ABA.5+%26+S%3AA262S&aaMutations1=S%3A153I%2CS%3A1258Q%2CN%3A151L&
![Schermata 2022-08-10 alle 20 26 06](https://user-images.githubusercontent.com/87669813/183988768-a071105e-e169-4777-94b4-720e28c84ab5.png)
![Schermata 2022-08-10 alle 20 26 17](https://user-images.githubusercontent.com/87669813/183988801-95b5c292-4208-4f3e-8a3f-8d8828910de2.png)

**Comment by AngieHinrichs** [comment]
I think I see your accesses in my web server logs, and as far as I can tell, they are completing OK, but slowly -- each one takes 4 to 5 minutes.  Maybe FireFox is giving up because it takes so long for my server to reply?  Can you try another web browser instead of FireFox?

**Comment by FedeGueli** [comment]
i usually chrome and when i try from.movile i know i have no possibility to success unless it is just a 3-10 sequences try.
Bit usually from.my pc it works very well. i suspecy that

**Comment by corneliusroemer** [comment]
@AngieHinrichs would it be possible to provide a URL that one can check later for results? This may be a better pattern than having someone wait for 5 minutes. It does happen that I accidentally close a window while I'm waiting for results and then all the work is lost - whereas if there was a dedicated URL with results awaiting I could recover.

**Comment by FedeGueli** [comment]
Great idea @corneliusroemer hope it will be easy to implement.
