### ISSUE TITLE
non-intuitive behavior for empty subsets, arguably a bug

### ISSUE THREAD

**Issue by jbloom** [yatisht/usher#268]
Running the command:
```
matUtils extract -i {input.mat} -s {input.samples} -o {output.mat}
```
where `{input.samples}` is an empty file returns the entire mutation-annotated tree.

I feel like this is a non-intuitive behavior, as the `-s` command is supposed to be for subsetting for the specified samples. I think it would be more intuitive to either return an empty mutation-annotated tree of raise an error.

(This is obviously most relevant to pipelines automatically generating different subsets, where if one happens to be empty instead you get back the whole mutation annotated tree.)

**Comment by yatisht** [comment]
@jmcbroome this should be an easy fix I think. Could you please have a look?

**Comment by jmcbroome** [comment]
Just added handling for this to a PR. Sorry I didn't consider that edge case before- thank you for raising the issue!

**Comment by yatisht** [comment]
PR merged!

**Comment by jbloom** [comment]
Great, thanks for fixing this!
