### ISSUE TITLE
Web Error: "Why did we not get EOF starting out with bignum"

### ISSUE THREAD

**Issue by corneliusroemer** [yatisht/usher#271]
@shay671 mentioned to me that he gets a weird error using USHER in the browser

![Screenshot_2022-09-14-20-52-03-10_0b2fce7a16bf2b728d6ffa28c8d60efb~2.jpg](https://user-images.githubusercontent.com/25161793/190239314-64172b56-54ff-42b6-a004-c0d93300c9fb.jpg)

Also encountered by @ryhisner I think

**Comment by AngieHinrichs** [comment]
Thanks -- so sorry about that, at >12 million sequences, the protobuf byte size has exceeded a constant that seemed safe enough when I wrote the code 2 years ago!  It is fixed on our test server (https://genome-test.gi.ucsc.edu/cgi-bin/hgPhyloPlace) and should be fixed on the main site (https://genome.ucsc.edu/cgi-bin/hgPhyloPlace) very soon.

Also found by @agamedilab and probably @FedeGueli too.

**Comment by shay671** [comment]
Wow, Indeed, who had thought two years ago that we would exceed 12M samples of SARS-CoV-2 sequences? 

Thank you, @AngieHinrichs, for your amazing work. It is a breakthrough that enables so many independent researchers to investigate and learn.

**Comment by AngieHinrichs** [comment]
It is fixed on the main site https://genome.ucsc.edu/cgi-bin/hgPhyloPlace 

Thanks again for reporting the error!  For future reference, bugs in the web interface can also be reported to the UCSC Genome Browser list genome-www@soe.ucsc.edu .

And thanks @shay671!  I couldn't do it without @yatisht's, @yceh's and @jmcbroome's work on UShER, matOptimize and matUtils, and we're so happy that people are finding it useful.
