### ISSUE TITLE
Usher should accept EPI_SETs exported directly, recognize EPI_ISL_14884799-EPI_ISL_14884801

### ISSUE THREAD

**Issue by corneliusroemer** [yatisht/usher#276]
GISAID exports EPI_ISLs in contracted form including things like `EPI_ISL_14884799-14884801`

Usher currently doesn't recognize these.

It would be great if you could adapt Usher to recognize these.

Here's a sample where the first item is not recognized:

```
EPI_ISL_14600253-14600254, EPI_ISL_14602583, EPI_ISL_14734321,
EPI_ISL_14805807, EPI_ISL_14808215, EPI_ISL_14818559,
EPI_ISL_14826899, EPI_ISL_14830592, EPI_ISL_14836256,
EPI_ISL_14836283, EPI_ISL_14836291, EPI_ISL_14836293,
EPI_ISL_14836296, EPI_ISL_14836298-14836299, EPI_ISL_14843218,
EPI_ISL_14849949, EPI_ISL_14852039, EPI_ISL_14870350,
EPI_ISL_14900850, EPI_ISL_14905914, EPI_ISL_14913252,
EPI_ISL_14914703, EPI_ISL_14915022, EPI_ISL_14915191,
EPI_ISL_14920429, EPI_ISL_14927575, EPI_ISL_14929498,
EPI_ISL_14930965, EPI_ISL_14931135, EPI_ISL_14937310,
EPI_ISL_14941296, EPI_ISL_14941356, EPI_ISL_14945844,
EPI_ISL_14946629, EPI_ISL_14960789
```

**Comment by russcd** [comment]
@AngieHinrichs I think this should be reasonably straightforward. Can we add that easily to the web interface? For matUtils, I am not sure it's necessary, but @jmcbroome could take a look?

**Comment by AngieHinrichs** [comment]
Yes, it should be straightforward.

**Comment by AngieHinrichs** [comment]
OK, I believe this is working on the test server: https://genome-test.gi.ucsc.edu/cgi-bin/hgPhyloPlace
(Also, @corneliusroemer, the extra Auspice config stuff you showed me, entropy panel and filters)

It will take a few weeks to percolate out to the main server unless I make a special request to our admins.

**Comment by corneliusroemer** [comment]
Excellent Angie! Thanks so much!

By the way I'm now forwarding requests to dev.usher.bio to your test server - easier than remembering that URL :p 

The main server is at usher.bio as usual

**Comment by corneliusroemer** [comment]
@AngieHinrichs regarding the Auspice config, @jameshadfield has written a guide for it now: https://github.com/nextstrain/docs.nextstrain.org/commit/3a3d12ba94077c0187110a691f710241648377ea

**Comment by corneliusroemer** [comment]
Tested it and can't get it to work. This was my input:
```
EPI_ISL_15160902
EPI_ISL_15199927-15199928
```

<img width="951" alt="image" src="https://user-images.githubusercontent.com/25161793/195482662-ef3f6eb2-9b45-4d31-a34f-0c722d6e21b4.png">


And this was the error:
<img width="798" alt="image" src="https://user-images.githubusercontent.com/25161793/195482654-544fa1d3-29c0-498f-95c6-14c1a48e4e0f.png">

**Comment by AngieHinrichs** [comment]
Sorry about that!  I will take a look...

and thanks for dev.usher.bio, awesome!

**Comment by AngieHinrichs** [comment]
Those IDs resolved to these tree names:
```
Canada/MB-CPL-515676/2022|EPI_ISL_15199928|2022-09-06
Canada/MB-CPL-515675/2022|EPI_ISL_15199927|2022-09-06
USA/VA-CDC-QDX41426322/2022|OP542979.1|2022-09-12
```
-- and then a matUtils command was exec'd to get subtrees, but it died, still trying to figure out why...

**Comment by AngieHinrichs** [comment]
Sorry, it was a change to my command-line conda environment that I didn't realize would affect the web server's matUtils executable (its libprotobuf shared object file disappeared -- because it was getting that from my conda environment in which it was compiled, yikes).

Fixed now.
