### ISSUE TITLE
Web USHeR -- dropdown to monkeypox not working

### ISSUE THREAD

**Issue by sidneymbell** [yatisht/usher#277]
Reverts the value to 'SARS-CoV-2' immediately after selection. If you'll point me in the right direction I'm happy to help fix this one if you'd like :)

Chrome Version 105.0.5195.125 (Official Build) (x86_64)

**Comment by AngieHinrichs** [comment]
Oh, that's not good!  Thanks for letting us know, I'll take a look.

**Comment by AngieHinrichs** [comment]
As a temporary workaround -- our test server doesn't have this problem:  https://genome-test.gi.ucsc.edu/cgi-bin/hgPhyloPlace

**Comment by AngieHinrichs** [comment]
It looks like there might have been a temporary problem with our "assembly hub" for monkeypox.  If you go to My Data -> Track Hubs in the top blue bar menu (or https://genome.ucsc.edu/cgi-bin/hgHubConnect), are there any error messages in red for "Monkeypox virus (MPXV-M5312_HM12_Rivers 2022)"?  If so, can you click the "Retry hub" button and then try https://genome.ucsc.edu/cgi-bin/hgPhyloPlace again?

**Comment by sidneymbell** [comment]
No error messages on the hubs page, and the dropdown is working now. Just
ran the example mpx data and it works :) Thanks for investigating!
