### ISSUE TITLE
ENH: Give internal nodes ids, so they can be labelled in Nextstrain URL

### ISSUE THREAD

**Issue by corneliusroemer** [yatisht/usher#284]
In order to allow Nextstrain share links to indicate the node that one was on when generating the link, you need some sort of unique id for the branch you're on.

This is not too hard to generate: https://github.com/corneliusroemer/nextstrain-deploy/blob/main/deploy.py#L17-L25

If a tree has such an internal node label, when you share a tree, the viewer will automatically zoom into that node.

See, e.g. https://next.nextstrain.org/monkeypox/hmpxv1/2022-10-18?label=id:1c0795b0

Note the id:1c0795b0 in the URL

It'd be neat if Usher added such unique labels to Nextstrain trees for more reproducible view sharing.

**Comment by jmcbroome** [comment]
Perhaps we could simply use our preexisting internal node IDs for this? Generally these follow the format "node_XXX" where XXX is their position in a tree traversal. Is there a limit on the formatting for Auspice UUIDs, or would any arbitrary string work?

**Comment by corneliusroemer** [comment]
Great idea! You can call these anything you like, no constraints at all.

**Comment by AngieHinrichs** [comment]
I already add the internal node_# identifiers to the JSON for the `"name"` attribute of non-leaf nodes (probably following what I saw in the nextstrain/ncov JSON a couple years ago): 
```
{ "name": "node_7278821", "branch_attrs": { "labels": { "nuc mutations": ...
```

So in addition to `"name"`, now I should also add it as `node["branch_attrs"]["labels"]["id"]` so it will be like this?:
```
{ "name": "node_7278821", "branch_attrs": { "labels": { "id": "node_7278821", "nuc mutations": ...
```
okey doke.  Having the ability to link to a particular node will be nice, it is frustrating when a node's mutations are homoplasic and reloading the URL with label=mutations results in an error about that.

**Comment by corneliusroemer** [comment]
Fabulous! Yes if you could add it as `node["branch_attrs"]["labels"]["id"]` that'd be amazing, then Auspice allows it to be stably linked to and zoomed into when sharing!

**Comment by corneliusroemer** [comment]
This works beautifully now, thanks @jmcbroome!
<img width="543" alt="image" src="https://user-images.githubusercontent.com/25161793/217566708-65579cc7-8d2b-480c-8edd-9461b6f76c21.png">

https://next.nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_26e5b_3b41d0.json?f_userOrOld=uploaded%20sample&label=id:node_9569558
