### ISSUE TITLE
ENH: Zoom Auspice into uploaded node, to make it easier to immediately see where your sample is

### ISSUE THREAD

**Issue by corneliusroemer** [yatisht/usher#285]
When I generate an Usher tree with 5000 samples, finding the uploaded sample on the tree can be quite a challenge.

It'd be nice if the link "view tree 1" could zoom directly into the subtree where the uploaded samples are.

This is possible if you implement #284 

That way users immediately can see their sample in the neighborhood - and still zoom out to see where the sample fits in more broadly.

**Comment by russcd** [comment]
I believe this has been resolved via the filtering config. Please reopen if I am incorrect or missed the meaning.
