### ISSUE TITLE
Ancestral node VCFs

### ISSUE THREAD

**Issue by lenorakepler** [yatisht/usher#291]
Hi there,

Thank you all so much for such a great tool! 

I was wondering if it is currently possible to output a VCF file of the "genotypes" of the ancestral nodes in a MAT, as is already done for the tips with the matUtils extract --write-vcf option.

Thanks!
Lenora Kepler

**Comment by yatisht** [comment]
This is already possible if you provide the internal node ids in the MAT instead of tip names. For e.g.

```
matUtils extract -s samples.txt -i in.pb -v out.vcf
```

Where samples.txt could contain a list of internal node labels:

```
node_6
node_25
```

Is this what you're looking for?

-Yatish

**Comment by lenorakepler** [comment]
That is exactly what I was looking for, thanks so much!
