### ISSUE TITLE
public tree: Apostrophes in clade names

### ISSUE THREAD

**Issue by theosanderson** [yatisht/usher#339]
(This is probably mostly a public-tree issue, but I guess there's a possibility it could also impact UShER in terms of Newick export.)

I noticed that the Cov2Tree Taxonium Tools pipeline got upset [yesterday](https://github.com/theosanderson/cov2tree/actions).  The error relates to TreeSwift complaining that the Newick file it gets (from the protobuf) is not what it considers a valid Newick file.

Looking into it, my current feeling is that these 
```
CoteD'Ivoire/MTMC_14_044/2021|OQ788229.1|2021-10-11):1,
CoteD'Ivoire/MTMC_14_133/2021|OQ788230.1|2021-10-15):1,
CoteD'Ivoire/MTMC_06_272/2022|OQ788228.1|2022-03-14,
```
are the issues, because TreeSwift expects apostrophes to be used as quotes to wrap literal names. It looks like they are recent additions.

Would it be possible to avoid those? No prob if not, I can add some code to handle this.

**Comment by theosanderson** [comment]
Thanks @AngieHinrichs

**Comment by AngieHinrichs** [comment]
Sorry, I didn't fix this in time for today's (2023-04-17) build, but it should be fixed in tomorrow's build.  I will check tomorrow to make sure.

**Comment by theosanderson** [comment]
Thanks again!
