### ISSUE TITLE
Cannot analyze XBB.1.5+T10204C samples

### ISSUE THREAD

**Issue by Over-There-Is** [yatisht/usher#346]
XBB.1.5+T10204C samples are placed on somewhere out of XBB.1.5
![2023-07-02 (1)](https://github.com/yatisht/usher/assets/38100637/a6fdd382-83bd-44d6-a59b-858a62e7ef04)
And XBB.1.16 samples split into 2 same branches.
![2023-07-02](https://github.com/yatisht/usher/assets/38100637/eaa5b1cb-4a6c-40f1-a2d5-d7d6cefa07e7)

**Comment by AngieHinrichs** [comment]
Thank you for reporting this @Over-There-Is .  Feel free to tag me (@AngieHinrichs) in a lineage-proposals or pango-designation issue for this kind of problem.  I hope to have the first problem with the misplacement of the T10204C branch fixed soon.  For the second issue with XBB.1.16, I'm not seeing the problem (at least in the 2023-07-05 tree).  If you still see the problem, please send me a sequence name or ID in the branch that seems misplaced.
