### ISSUE TITLE
Exclusion of reference sequence in placement

### ISSUE THREAD

**Issue by brmagalis** [yatisht/usher#35]
After building the vcf using fasta2usher, it seems as though the reference sequence itself is actually being placed in the tree, which results in several copies of the reference sequence over time. I realize that matUtils can be used to filter this out, but I am not able to get matUtils installed on my hpc, so I was wondering if there was a trick to preventing the reference sequence from being placed when you can't use matUtils?

**Comment by yatisht** [comment]
@lgozasht can you please help @brmagalis resolve this issue? I think this is related to fasta2usher.

**Comment by lgozasht** [comment]
Hi @brmagalis 

Sorry to hear you're having this issue.
Would you mind sending me your input data and command to lgozasht@ucsc.edu so I can try to resolve this ?

Landen

**Comment by brmagalis** [comment]
Certainly! Attached are the files, and I am simply using the fasta2usher.py with the following:

 

python Fasta2UShER.py -inpath ${i} -output ${i}.vcf -reference cov_reference.fasta            

 

-- 

Brittany Rife Magalis, PhD

Research Assistant Scientist, UF College of Medicine

Department of Pathology, Immunology, and Laboratory Medicine

Emerging Pathogens Institute

Gainesville, FL 32611

Phone: +1 (540) 383-1395

**Comment by lgozasht** [comment]
Hi @brmagalis, 

I can't seem to replicate this. Is it possible that you included the reference sequence in your -inpath directory?

**Comment by brmagalis** [comment]
No, but that’s not the problem. I meant to tell you to replace my variables with whatever directory and name you‘d like. The issue comes when I place the sequences on the tree, and it always includes the ref seq itself as a sample, which then accumulates in my tree. Yatish had said it might be the fasta2usher.py, but I can give you the tree as well, so you can see what I’m talking about? Because the vcf seems like a normal vcf to me and doesn’t include the ref seq as an additional separate sample/column.

**Comment by yatisht** [comment]
Hi @brmagalis,

Yes, please send me the files (input tree and vcf). You can also email them to me at yturakhi@ucsc.edu. UShER should not be placing any sample that is not in the vcf and I have never encountered something like that!

-Yatish

**Comment by yatisht** [comment]
Are you still facing this issue, @brmagalis. Please send me the relevant files, if so.

-Yatish

**Comment by brmagalis** [comment]
Yatish,

 

I’m sorry, I honestly haven’t had time to take a look. I will try to get to this later this week and email you as soon as I test it out again!

 

-- 

Brittany Rife Magalis, PhD

Research Assistant Scientist, UF College of Medicine

Department of Pathology, Immunology, and Laboratory Medicine

Emerging Pathogens Institute

Gainesville, FL 32611

Phone: +1 (540) 383-1395

**Comment by yatisht** [comment]
Hi @brmagalis ,

I am going to close this issue now since we've moved on from Fasta2UShER. Please let us know if you face issues even with the new instructions.

-Yatish
