### ISSUE TITLE
Usher crashing when uploading any amount of data

### ISSUE THREAD

**Issue by corneliusroemer** [yatisht/usher#373]
I've been trying to use usher and it seems to crash:
<img width="1072" alt="image" src="https://github.com/yatisht/usher/assets/25161793/80d9f4fb-2639-44b5-a2e3-84f549be127c">

Even if I send fairly little data (10 SC2 sequences)

**Comment by AngieHinrichs** [comment]
Is that dev.usher.bio or main usher.bio?  (I am on vacation this week so I will be slow to respond, sorry)

**Comment by corneliusroemer** [comment]
It seems to have worked itself out!

It was definitely on main usher, but possibly both.

Enjoy your vacation! I'll close the issue and reopen if something reoccurs.
