### ISSUE TITLE
Couldn't open inputMsa.fa

### ISSUE THREAD

**Issue by dezordi** [yatisht/usher#41]
Hi all,

My name is Filipe and I'm testing the usher implement via docker following the steps present in the README file.

I was able to perform all testing analysis with usher, but when I tried to run the generation of vcf file following the tutorial, I got the error:

> Couldn't open inputMsa.fa , No such file or directory

The line was:
`python3 scripts/Fasta2UShER.py -reference ./test/NC_045512v2.fa  -inpath ./test/Fasta2UShER/ -unaligned -output ./test/test_merged.vcf`

I ran the line in the path /HOME/usher inside the docker container.

I realize that a file called inputMsa.fa was created in /HOME/usher/scripts/ path.

So how can I proceed?

**Comment by yatisht** [comment]
Hi Filipe,

Thanks for trying UShER and flagging the issue.

@lgozasht Please address this issue, when possible. Fasta2UShER is finding various issues with users - we should consider rewriting it or removing it altogether (replacing it by simple CLI commands).

**Comment by yatisht** [comment]
Hi Filipe,

We have removed Fasta2UShER and replaced it with simple common line instructions in our README, see https://github.com/yatisht/usher#converting-raw-sequences-into-vcf-for-usher-input. Please try this out and let us know if you still face any issues.

Best,
Yatish

**Comment by dezordi** [comment]
Dear Yatish,

thank you very much, as soon as I perform the tests I let my feedback here.

Best,
Filipe

**Comment by dezordi** [comment]
> Hi Filipe,
> 
> We have removed Fasta2UShER and replaced it with simple common line instructions in our README, see https://github.com/yatisht/usher#converting-raw-sequences-into-vcf-for-usher-input. Please try this out and let us know if you still face any issues.
> 
> Best,
> Yatish

Hi Yatish,

I re-run the tests following this new mode and everything ran well, thanks.
