### ISSUE TITLE
suggestion: output files

### ISSUE THREAD

**Issue by roblanf** [yatisht/usher#5]
As far as I can tell, currently the output is all just printed. I guess the intention is that one pipes this to a log file and then extracts the relevant information. But this may not be all that desirable for a couple of reasons. First, that log might get enormous (e.g. placing 50K new samples on a 50K tree). Second, it adds friction to downstream processing, because users will need to roll their own scripts to extract the information they want. The latter makes the program fragile in the sense that updating UShER could easily break downstream data-extraction scripts. It seems better in this sense to rely on outputting files to standard formats that are unlikely to change (at least between major versions).

Here are some suggestions for discussion:

1. Allow users to turn off the printing e.g. with `--quiet`
2. Allow users to specify which output files they want to save, e.g. with `--out-tree`, `--out-uncondensed-tree`, '--out-parsimony-table` etc.

The latter means users have control over what gets saved in the first place, as well as giving an opportunity to explain the format and details of every possible output file in the README.

**Comment by yatisht** [comment]
Hi Rob,

I made some major changes just now to write output files to a user-specified directory using **--outdir**. There are also some changes to the command line options but all help is available in the README plus the help message. This is not the same as what you're asking for, but I had already started implementing a similar suggestion made by @AngieHinrichs, though I can easily change to user-specified filenames for each file if you don't like this. Please let me know. 

-Yatish
