### ISSUE TITLE
segmentation fault when writing updated pb file when all sequences are already in the file

### ISSUE THREAD

**Issue by rmcolq** [yatisht/usher#51]
I've been running usher in a nexflow pipeline, creating an initial start tree and sequentially updating with chunks of a large fasta. I've been getting a segfault _only_ when I restart the nextflow pipeline, with the end of log reading:
```Collapsing input tree.
  Completed in 6 msec 
  
  Condensing identical sequences. 
  WARNING: tree contains condensed nodes. It may be condensed already!
  Writing condensed input tree to file trees/condensed-tree.nh
  Completed in 35 msec 
  
  Found 0 missing samples.
  
  Writing uncondensed final tree to file trees/uncondensed-final-tree.nh 
  The parsimony score for this tree is: 81342 
  Completed in 21 msec 
  
  Saving mutation-annotated tree object to file (after condensing identical sequences) cog_gisaid_B.dequote.false.false.pb
  .command.sh: line 3: 18339 Segmentation fault: 11  usher -i cog_gisaid_B.dequote.false.pb --vcf lineage_Bplus.new.5.with_reference.vcf --threads 8 --save-mutation-annotated-tree cog_gisaid_B.dequote.false.false.pb --collapse-tree --write-uncondensed-final-tree --outdir trees
```
 
Could this be caused by there not existing any new sequences?

**Comment by yatisht** [comment]
I have never encountered an error like this, not even when there are no new sequences to be placed. Is it possible for you to send the files across? You can also email them to me at yturakhi@ucsc.edu. 

-Yatish

**Comment by rmcolq** [comment]
Thank you! Cleaning the tree and fasta to remove unexpected symbols seems to have fixed this like you suggested! Might be good to have something which catches unexpected symbols in input earlier on? It surprised me that this was the cause given I only got the segfault when the protobuf was written out at the end.

**Comment by yatisht** [comment]
Oh, wonderful. I'll close this issue in that case. I'll also try and fix the parsing issue you suggested.
