### ISSUE TITLE
suggestion: output file for --print-parsimony-scores-per-node

### ISSUE THREAD

**Issue by roblanf** [yatisht/usher#6]
Right now this (awesome) function outputs a text stream. It's fine, and easy to grep things from if you know what you're doing. But that will exclude a lot of potential users. 

The output is already presented as a series of tsv files, but I think it makes sense to roll it into one single tsv where:

rows are nodes and leaves of the input tree
cols are named for each sample

This is more compact than the current output, and easier to deal with for downstream processing too.

**Comment by yatisht** [comment]
I have a modified version of this now. The file generated is called `parsimony-scores.tsv` in the output directory. It has 5 columns:
1. Sample name
2. Tree node   
3. Is the sample placement at tree node optimal (y/n)   
4. Parsimony score for placing the sample at the tree node
5. Parsimony-increasing mutations (for optimal nodes)
