### ISSUE TITLE
Segmentation fault when running Quick Start

### ISSUE THREAD

**Issue by lczech** [yatisht/usher#62]
Hi there,

I've tried to follow the [Quick Start](https://usher-wiki.readthedocs.io/en/latest/QuickStart.html), but at the first usher command, which is supposed to create the `global_phylo.pb` file, I get a segfault. Debugging the core dump with `gdb usher core`, I get:

```
(gdb) bt
#0  Mutation_Annotated_Tree::write_newick_string (ss=..., T=..., node=0x0, print_internal=true, print_branch_len=true, retain_original_branch_len=false, uncondense_leaves=false) at /usr/local/src/conda/usher-0.2.1/src/mutation_annotated_tree.cpp:158
#1  0x000055e138d3544a in Mutation_Annotated_Tree::get_newick_string[abi:cxx11](Mutation_Annotated_Tree::Tree const&, Mutation_Annotated_Tree::Node*, bool, bool, bool, bool) (T=..., node=0x0, print_internal=<optimized out>, print_branch_len=<optimized out>, 
    retain_original_branch_len=<optimized out>, uncondense_leaves=false) at /usr/local/src/conda/usher-0.2.1/src/mutation_annotated_tree.cpp:297
#2  0x000055e138d2232d in main (argc=<optimized out>, argv=<optimized out>) at /usr/local/src/conda/usher-0.2.1/src/usher.cpp:475
```

This is using usher installed via conda 4.9.2 on Ubuntu 20.04.2 LTS.

Cheers
Lucas

**Comment by yatisht** [comment]
Hi Lucas,

Thanks for bringing this to our attention. I think the URLs to the wget command might be causing the problem (it probably downloads the HTML file instead of the raw file). Could you please retry after the following wget commands:

```
wget https://raw.githubusercontent.com/yatisht/usher/master/test/global_phylo.nh
wget https://raw.githubusercontent.com/yatisht/usher/master/test/global_samples.vcf
```

@bpt26 we should fix this on the wiki.

-Yatish

**Comment by yatisht** [comment]
Hi Lucas,

Were you able to get this to work? 

-Yatish

**Comment by lczech** [comment]
Hey @yatisht,

thanks, that worked. I would however also recommend to improve the error messages in Usher, to avoid having user to run gdb to figure out why a file could not be loaded :-)

Cheers 
Lucas

**Comment by yatisht** [comment]
Got it, will do!
