### ISSUE TITLE
matUtils looks for metadata in output directory

### ISSUE THREAD

**Issue by Jeltje** [yatisht/usher#72]
I'm running this on a docker container:

`docker run -ti --rm -v $(pwd):/mydata -w /mydata yatisht/usher`
Then, on the container:
`matUtils extract -i protobufs/myTree.pb -M CDPH_Full_Tree.meta.tsv -K mysamples:500 -d myoutput`
gets
```
Loading input MAT file protobufs/myTree.pb.
Completed in 19818 msec

Checking for and applying sample selection arguments
No sample selection arguments passed; using full input tree for further output.
Completed in 893 msec

ERROR: Could not open the file: /mydata/myoutput/CDPH_Full_Tree.meta.tsv!
```
The tree is of course in `/mydata/CDPH_Full_Tree.meta.tsv`, not in `/mydata/myoutput`

**Comment by yatisht** [comment]
@jmcbroome Will you please handle this? Jeltje need this soon for Terra integration. You can see how UShER is handling filepaths for reference.

**Comment by Jeltje** [comment]
More info. Here's an attempted Cromwell run (with the irritatingly long file paths, apologies for that):
```
matUtils extract -M /cromwell-executions/matUtils/eece3cd9-a150-4b8b-930c-dc6209f036e5/call-Extract/inputs/1131901398/CDPH_Full_Tree.meta.tsv -i /cromwell-executions/matUtils/eece3cd9-a150-4b8b-930c-dc6209f036e5/call-Extract/inputs/-1165080241/public.plusGisaid.2021-05-13.plusCA.plusEskin.2021-05-13.pb -s /cromwell-executions/matUtils/eece3cd9-a150-4b8b-930c-dc6209f036e5/call-Extract/inputs/1131901398/test_samples.txt:500
```
Which dies with
```
ERROR: Could not open the file: /cromwell-executions/matUtils/48dd3619-0bd7-4b6b-a714-56991a43b700/call-Extract/execution//cromwell-executions/matUtils/48dd3619-0bd7-4b6b-a714-56991a43b700/call-Extract/inputs/1131901398/CDPH_Full_Tree.meta.tsv!
```
It's appending the metadata file path to the workdir (note the double slash after /execution)

**Comment by jmcbroome** [comment]
Hi Jeltje, sorry about this issue, just a mistake with boilerplate code for file parsing on my part. I've just pushed a fix, let me know if you encounter any further issues.

**Comment by Jeltje** [comment]
Thanks! Will let you know if I have any more issues.
