### ISSUE TITLE
add usher -v/--version flag to print version

### ISSUE THREAD

**Issue by kapsakcj** [yatisht/usher#76]
Hi Yatish, I would like to request additional flags `usher -v` and `usher --version` for printing the version of UShER to STDOUT

I looked around in the docs & usher help options and couldn't find anything similar.

Is this something that you could add in the future?

**Comment by yatisht** [comment]
Thank you for your suggestion. We have added `--version` in UShER and it displays the version number in STDERR. Since `-v` is reserved for passing in the VCF files, we don't have a shorthand notation for `--version`.

**Comment by kapsakcj** [comment]
perfect, thank you!
