### ISSUE TITLE
Installing version=0.3.1

### ISSUE THREAD

**Issue by IsabelFE** [yatisht/usher#87]
I dowloaded the 0.3.1 release and installed using the Installation scripts, when I do `usher --version` I get UShER (v0.3.0). With `conda install` I get only 0.2.0.

Since Pangolin requires 0.3.1, is there an easy way to get both Pangolin + Usher installed on the same environment. 

Thanks

**Comment by kapsakcj** [comment]
I've noticed this as well. When I install UShER 0.3.1 via conda, `usher --version` report v0.3.0. 

Here's the `environment.yml` used to build the conda environment:
```
$ cat environment.yml
name: pangolin
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython=1.74
  - minimap2>=2.16
  - pip=19.3.1
  - python>=3.7
  - snakemake-minimal>=5.13
  - gofasta
  - usher=0.3.1-0
  - pip:
    - pandas==1.0.1
    - git+https://github.com/cov-lineages/pangoLEARN.git@2021-06-05
    - git+https://github.com/cov-lineages/scorpio.git@v0.3
    - git+https://github.com/cov-lineages/constellations.git@v0.0.4
```

Here's the output from within the Pangolin docker container that I've helped to develop:
```
$ conda list | grep usher
usher                     0.3.1                h7b4d82f_0    bioconda
$ usher --version
UShER (v0.3.0)
```

**Comment by IsabelFE** [comment]
@kapsakcj , hoe did you installed UShER 0.3.1 via conda? I haven't only been able to instal 0.2.0 with conda

**Comment by kapsakcj** [comment]
I manually edited the environment.yml file (see above) that is provided with Pangolin source code. The edit was to pin the UShER version to 0.3.1-0

 Then built the conda environment with this command: `conda env create -f environment.yml`

full Pangolin install directions here: https://cov-lineages.org/pangolin_docs/installation.html

**Comment by IsabelFE** [comment]
@kapsakcj thanks! The GitHub environment.yml was updated 7h ago to fix this also ☺️
